# Generated by Django 4.2.6 on 2023-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address_uk", models.TextField()),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[("new", "New (£1200)"), ("used", "Used (£650)")],
                        max_length=5,
                    ),
                ),
                ("requested_delivery_date", models.DateField()),
            ],
        ),
    ]
