# Generated by Django 4.2.6 on 2023-10-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Delivery", "Pending Delivery"),
                            ("Picked Up", "Picked Up"),
                            ("Confirmed Picked Up", "Confirmed Picked Up"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Pending Delivery",
                        max_length=20,
                    ),
                ),
                ("delivery_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_service.customer",
                    ),
                ),
            ],
        ),
    ]
