# Generated by Django 4.2.6 on 2023-10-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Payment", "Pending Payment"),
                            ("Payment Processed", "Payment Processed"),
                        ],
                        default="Pending Payment",
                        max_length=20,
                    ),
                ),
                ("stripe_bank_details", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_service.customer",
                    ),
                ),
            ],
        ),
    ]
